Repository Vegan-Life/VeganLife-Backend, pull requests merged in 2023-12, with the labels that each got.

#20 JwtAuthenticationFilter 구현
  src/main/java/com/konggogi/veganlife/global/config/SecurityConfig.java
  src/main/java/com/konggogi/veganlife/global/exception/ErrorCode.java
  src/main/java/com/konggogi/veganlife/global/security/exception/InvalidJwtException.java
  src/main/java/com/konggogi/veganlife/global/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/konggogi/veganlife/global/util/JwtUtils.java
Labels: feature

#22 LoogerAop와 TimeTraceAop 구현
  src/main/java/com/konggogi/veganlife/global/aop/LoggerAop.java
  src/main/java/com/konggogi/veganlife/global/aop/TimeTraceAop.java
  src/main/java/com/konggogi/veganlife/global/aop/domain/MethodSignature.java
  src/main/java/com/konggogi/veganlife/global/util/AopUtils.java
  src/main/resources/application-local.yml
Labels: feature

#30 카카오 소셜 로그인
  build.gradle
  src/main/java/com/konggogi/veganlife/global/aop/LoggerAop.java
  src/main/java/com/konggogi/veganlife/global/aop/TimeTraceAop.java
  src/main/java/com/konggogi/veganlife/global/config/SecurityConfig.java
  src/main/java/com/konggogi/veganlife/global/exception/ErrorCode.java
  src/main/java/com/konggogi/veganlife/member/controller/OauthController.java
  src/main/java/com/konggogi/veganlife/member/domain/Member.java
  src/main/java/com/konggogi/veganlife/member/domain/oauth/KakaoUserInfo.java
  src/main/java/com/konggogi/veganlife/member/domain/oauth/OauthUserInfo.java
  src/main/java/com/konggogi/veganlife/member/dto/request/OauthRequest.java
  src/main/java/com/konggogi/veganlife/member/dto/response/OauthLoginResponse.java
  src/main/java/com/konggogi/veganlife/member/exception/UnsupportedProviderException.java
  src/main/java/com/konggogi/veganlife/member/service/OauthService.java
  src/main/java/com/konggogi/veganlife/member/service/OauthUserInfoFactory.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
Labels: feature

#32 OauthController에서 OAuthLoginResponse를 생성하도록 변경
  src/main/java/com/konggogi/veganlife/member/controller/OauthController.java
  src/main/java/com/konggogi/veganlife/member/dto/response/OauthLoginResponse.java
  src/main/java/com/konggogi/veganlife/member/service/OauthService.java
Labels: feature

#33 OauthProvider 구현 및 Custom Converter 생성
  src/main/java/com/konggogi/veganlife/global/config/WebConfig.java
  src/main/java/com/konggogi/veganlife/member/controller/OauthController.java
  src/main/java/com/konggogi/veganlife/member/domain/Member.java
  src/main/java/com/konggogi/veganlife/member/domain/converter/OauthProviderConverter.java
  src/main/java/com/konggogi/veganlife/member/domain/oauth/KakaoUserInfo.java
  src/main/java/com/konggogi/veganlife/member/domain/oauth/OauthProvider.java
  src/main/java/com/konggogi/veganlife/member/domain/oauth/OauthUserInfo.java
  src/main/java/com/konggogi/veganlife/member/service/OauthService.java
  src/main/java/com/konggogi/veganlife/member/service/OauthUserInfoFactory.java
Labels: feature

#37 네이버 소셜 로그인
  src/main/java/com/konggogi/veganlife/member/domain/oauth/NaverUserInfo.java
  src/main/java/com/konggogi/veganlife/member/service/OauthService.java
  src/main/java/com/konggogi/veganlife/member/service/OauthUserInfoFactory.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
Labels: feature

#39 gender 관련 메서드 삭제
  src/main/java/com/konggogi/veganlife/member/domain/Member.java
  src/main/java/com/konggogi/veganlife/member/domain/oauth/KakaoUserInfo.java
  src/main/java/com/konggogi/veganlife/member/domain/oauth/NaverUserInfo.java
  src/main/java/com/konggogi/veganlife/member/domain/oauth/OauthUserInfo.java
  src/main/java/com/konggogi/veganlife/member/service/OauthService.java
Labels: feature

#47 [#46] chore: `application.yml`에 h2-console 관련 설정 추가
  src/main/resources/application-local.yml
  src/main/resources/application-test.yml
  src/main/resources/application.yml
Labels: bug

#45 회원 가입 구현
  build.gradle
  src/main/java/com/konggogi/veganlife/global/config/SecurityConfig.java
  src/main/java/com/konggogi/veganlife/global/exception/ErrorCode.java
  src/main/java/com/konggogi/veganlife/member/controller/MemberController.java
  src/main/java/com/konggogi/veganlife/member/controller/OauthController.java
  src/main/java/com/konggogi/veganlife/member/controller/dto/request/MemberRegisterRequest.java
  src/main/java/com/konggogi/veganlife/member/controller/dto/request/MemberRegisterResponse.java
  src/main/java/com/konggogi/veganlife/member/controller/dto/request/OauthRequest.java
  src/main/java/com/konggogi/veganlife/member/controller/dto/response/OauthLoginResponse.java
  src/main/java/com/konggogi/veganlife/member/domain/Member.java
  src/main/java/com/konggogi/veganlife/member/domain/mapper/MemberMapper.java
  src/main/java/com/konggogi/veganlife/member/dto/request/OauthRequest.java
  src/main/java/com/konggogi/veganlife/member/dto/response/OauthLoginResponse.java
  src/main/java/com/konggogi/veganlife/member/exception/DuplicateNicknameException.java
  src/main/java/com/konggogi/veganlife/member/repository/MemberRepository.java
  src/main/java/com/konggogi/veganlife/member/service/MemberService.java
  src/main/java/com/konggogi/veganlife/member/service/OauthService.java
Labels: feature

#49 MemberMapper 메서드 이름 변경
  src/main/java/com/konggogi/veganlife/member/controller/MemberController.java
  src/main/java/com/konggogi/veganlife/member/domain/mapper/MemberMapper.java
  src/main/java/com/konggogi/veganlife/member/service/MemberService.java
Labels: refactor

#51 jvm args 설정 삭제
  build.gradle
  src/main/java/com/konggogi/veganlife/member/domain/mapper/MemberMapper.java
Labels: fix

#52 OauthMapper 구현
  src/main/java/com/konggogi/veganlife/member/controller/OauthController.java
  src/main/java/com/konggogi/veganlife/member/controller/dto/response/OauthLoginResponse.java
  src/main/java/com/konggogi/veganlife/member/domain/mapper/OauthMapper.java
Labels: refactor

#53 OauthController Map Struct 사용하도록 변경
  src/main/java/com/konggogi/veganlife/member/controller/OauthController.java
  src/main/java/com/konggogi/veganlife/member/domain/mapper/MemberMapper.java
  src/main/java/com/konggogi/veganlife/member/domain/mapper/OauthMapper.java
Labels: refactor

#55 회원 탈퇴 로직 구현
  src/main/java/com/konggogi/veganlife/global/exception/ErrorCode.java
  src/main/java/com/konggogi/veganlife/global/exception/NotFoundEntityException.java
  src/main/java/com/konggogi/veganlife/member/controller/MemberController.java
  src/main/java/com/konggogi/veganlife/member/service/MemberService.java
Labels: feature

#56 MemberRegisterRequest validation 추가
  src/main/java/com/konggogi/veganlife/member/controller/dto/request/MemberRegisterRequest.java
  src/main/java/com/konggogi/veganlife/member/domain/Gender.java
  src/main/java/com/konggogi/veganlife/member/domain/VegetarianType.java
Labels: feature

#60 기초대사량 bmr과 일일 권장 섭취량 계산 메서드 추가
  src/main/java/com/konggogi/veganlife/member/domain/Member.java
  src/main/java/com/konggogi/veganlife/member/service/MemberService.java
Labels: feature

#67 MemberProfileResponse의 age 필드 삭제
  src/main/java/com/konggogi/veganlife/member/controller/dto/response/MemberProfileResponse.java
Labels: feature

#68 소셜 로그인시 회원가입
  src/main/java/com/konggogi/veganlife/global/security/jwt/RefreshToken.java
  src/main/java/com/konggogi/veganlife/global/util/JwtUtils.java
  src/main/java/com/konggogi/veganlife/member/controller/MemberController.java
  src/main/java/com/konggogi/veganlife/member/controller/OauthController.java
  src/main/java/com/konggogi/veganlife/member/controller/dto/request/MemberRegisterRequest.java
  src/main/java/com/konggogi/veganlife/member/controller/dto/request/MemberRegisterResponse.java
  src/main/java/com/konggogi/veganlife/member/controller/dto/response/OauthLoginResponse.java
  src/main/java/com/konggogi/veganlife/member/domain/Member.java
  src/main/java/com/konggogi/veganlife/member/domain/mapper/MemberMapper.java
  src/main/java/com/konggogi/veganlife/member/repository/RefreshTokenRepository.java
  src/main/java/com/konggogi/veganlife/member/service/MemberService.java
Labels: refactor

#71 마이페이지 조회 응답 birthYear 필드 추가
  src/main/java/com/konggogi/veganlife/member/controller/dto/response/MemberProfileResponse.java
Labels: refactor

#70 회원 추가 정보 입력 기능 구현
  src/main/java/com/konggogi/veganlife/member/controller/MemberController.java
  src/main/java/com/konggogi/veganlife/member/controller/OauthController.java
  src/main/java/com/konggogi/veganlife/member/controller/dto/request/MemberInfoRequest.java
  src/main/java/com/konggogi/veganlife/member/controller/dto/response/MemberInfoResponse.java
  src/main/java/com/konggogi/veganlife/member/controller/dto/response/OauthLoginResponse.java
  src/main/java/com/konggogi/veganlife/member/domain/Member.java
  src/main/java/com/konggogi/veganlife/member/domain/mapper/MemberMapper.java
  src/main/java/com/konggogi/veganlife/member/service/MemberService.java
Labels: feature

#74 JpaAuditing 오류 수정
  src/main/java/com/konggogi/veganlife/VeganlifeApplication.java
  src/main/java/com/konggogi/veganlife/global/config/JpaAuditingConfig.java
  src/test/java/com/konggogi/veganlife/VeganlifeApplicationTests.java
Labels: bug

#77 식단 메뉴 검색 기능 구현, MapStruct 에러 해결
  .gitignore
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/meal-data.adoc
  src/main/java/com/konggogi/veganlife/mealdata/controller/MealDataController.java
  src/main/java/com/konggogi/veganlife/mealdata/controller/dto/response/MealDataListResponse.java
  src/main/java/com/konggogi/veganlife/mealdata/domain/IntakeUnit.java
  src/main/java/com/konggogi/veganlife/mealdata/domain/MealData.java
  src/main/java/com/konggogi/veganlife/mealdata/domain/MealDataType.java
  src/main/java/com/konggogi/veganlife/mealdata/domain/mapper/MealDataMapper.java
  src/main/java/com/konggogi/veganlife/mealdata/repository/MealDataRepository.java
  src/main/java/com/konggogi/veganlife/mealdata/service/MealDataQueryService.java
  src/test/java/com/konggogi/veganlife/config/MapStructConfig.java
  src/test/java/com/konggogi/veganlife/mealdata/controller/MealDataControllerTest.java
  src/test/java/com/konggogi/veganlife/mealdata/fixture/MealDataFixture.java
  src/test/java/com/konggogi/veganlife/mealdata/repository/MealDataRepositoryTest.java
  src/test/java/com/konggogi/veganlife/mealdata/service/MealDataQueryServiceTest.java
  src/test/java/com/konggogi/veganlife/support/docs/ApiDocumentUtils.java
  src/test/java/com/konggogi/veganlife/support/docs/RestDocsTest.java
Labels: bug, feature

#80 @Tracnsactional 애노테이션 삭제
  src/main/java/com/konggogi/veganlife/member/service/OauthService.java
Labels: refactor

#81 액세스 토큰 재발급 로직 구현
  src/main/java/com/konggogi/veganlife/global/config/SecurityConfig.java
  src/main/java/com/konggogi/veganlife/global/exception/ErrorCode.java
  src/main/java/com/konggogi/veganlife/global/security/exception/MismatchTokenException.java
  src/main/java/com/konggogi/veganlife/global/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/konggogi/veganlife/global/util/JwtUtils.java
  src/main/java/com/konggogi/veganlife/member/controller/AuthController.java
  src/main/java/com/konggogi/veganlife/member/controller/dto/request/ReissueRequest.java
  src/main/java/com/konggogi/veganlife/member/controller/dto/response/AuthResponse.java
  src/main/java/com/konggogi/veganlife/member/domain/mapper/AuthMapper.java
  src/main/java/com/konggogi/veganlife/member/service/MemberService.java
Labels: feature

#83 명령을 수행하는 MemberService와 조회를 수행하는 MemberQueryService로 분리
  src/main/java/com/konggogi/veganlife/member/controller/AuthController.java
  src/main/java/com/konggogi/veganlife/member/controller/MemberController.java
  src/main/java/com/konggogi/veganlife/member/service/MemberQueryService.java
  src/main/java/com/konggogi/veganlife/member/service/MemberService.java
Labels: refactor

#85 [#79] chore: build.gradle restdocs 관련 task 수정
  build.gradle
Labels: bug

#87 Restdocs에서 자주 사용하는 Descriptor 구현
  src/docs/asciidoc/meal-data.adoc
  src/test/java/com/konggogi/veganlife/mealdata/controller/MealDataControllerTest.java
  src/test/java/com/konggogi/veganlife/support/docs/RestDocsTest.java
Labels: test

#91 AOP request parmeter가 들어오지 않았을 경우 예외 처리 해결
  src/main/java/com/konggogi/veganlife/global/aop/LoggerAop.java
Labels: bug

#92 Logging Util 구현
  src/main/java/com/konggogi/veganlife/global/advice/common/GlobalControllerAdvice.java
  src/main/java/com/konggogi/veganlife/global/aop/LoggerAop.java
  src/main/java/com/konggogi/veganlife/global/util/AopUtils.java
  src/main/java/com/konggogi/veganlife/global/util/LoggingUtils.java
Labels: feature

#97 Method Argument 관련 예외 핸들링
  src/main/java/com/konggogi/veganlife/global/advice/common/GlobalControllerAdvice.java
  src/main/java/com/konggogi/veganlife/global/util/LoggingUtils.java
Labels: feature

#100 Member 관련 테스트 코드 구현
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/member.adoc
  src/main/java/com/konggogi/veganlife/member/domain/Member.java
  src/test/java/com/konggogi/veganlife/member/controller/MemberControllerTest.java
  src/test/java/com/konggogi/veganlife/member/domain/MemberTest.java
  src/test/java/com/konggogi/veganlife/member/fixture/MemberFixture.java
  src/test/java/com/konggogi/veganlife/member/repository/MemberRepositoryTest.java
  src/test/java/com/konggogi/veganlife/member/service/MemberQueryServiceTest.java
  src/test/java/com/konggogi/veganlife/member/service/MemberServiceTest.java
Labels: test

#102 Member, Auth 관련 에러 핸들링
  src/main/java/com/konggogi/veganlife/global/advice/member/MemberControllerAdvice.java
  src/main/java/com/konggogi/veganlife/member/controller/MemberController.java
Labels: feature

#103 Auth, OAuth 관련 테스트 구현
  src/docs/asciidoc/auth.adoc
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/member.adoc
  src/docs/asciidoc/oauth.adoc
  src/main/java/com/konggogi/veganlife/global/advice/member/MemberControllerAdvice.java
  src/main/java/com/konggogi/veganlife/member/controller/AuthController.java
  src/test/java/com/konggogi/veganlife/config/MapStructConfig.java
  src/test/java/com/konggogi/veganlife/member/controller/AuthControllerTest.java
  src/test/java/com/konggogi/veganlife/member/controller/MemberControllerTest.java
  src/test/java/com/konggogi/veganlife/member/controller/OauthControllerTest.java
  src/test/java/com/konggogi/veganlife/member/domain/oauth/OauthProviderTest.java
  src/test/java/com/konggogi/veganlife/member/fixture/MemberFixture.java
  src/test/java/com/konggogi/veganlife/member/service/OauthUserInfoFactoryTest.java
Labels: test

#105 회원 프로필 수정 구현
  src/docs/asciidoc/member.adoc
  src/main/java/com/konggogi/veganlife/member/controller/MemberController.java
  src/main/java/com/konggogi/veganlife/member/controller/dto/request/MemberProfileRequest.java
  src/main/java/com/konggogi/veganlife/member/domain/Member.java
  src/main/java/com/konggogi/veganlife/member/service/MemberService.java
  src/test/java/com/konggogi/veganlife/member/controller/MemberControllerTest.java
  src/test/java/com/konggogi/veganlife/member/domain/MemberTest.java
  src/test/java/com/konggogi/veganlife/member/service/MemberServiceTest.java
Labels: feature

#108 권장 섭취량 조회 API 구현
  src/docs/asciidoc/member.adoc
  src/main/java/com/konggogi/veganlife/member/controller/MemberController.java
  src/main/java/com/konggogi/veganlife/member/controller/dto/response/DailyNutrientsResponse.java
  src/main/java/com/konggogi/veganlife/member/domain/mapper/MemberMapper.java
  src/test/java/com/konggogi/veganlife/member/controller/MemberControllerTest.java
Labels: feature

#110 권장 섭취량 조회 API 응답 Dto, 메서드명 변경
  src/main/java/com/konggogi/veganlife/member/controller/MemberController.java
  src/main/java/com/konggogi/veganlife/member/controller/dto/response/RecommendNutrientsResponse.java
  src/main/java/com/konggogi/veganlife/member/domain/mapper/MemberMapper.java
Labels: refactor

#112 MealData 엔티티 수정
  src/docs/asciidoc/meal-data.adoc
  src/main/java/com/konggogi/veganlife/mealdata/controller/MealDataController.java
  src/main/java/com/konggogi/veganlife/mealdata/controller/dto/response/MealDataListResponse.java
  src/main/java/com/konggogi/veganlife/mealdata/domain/IntakeUnit.java
  src/main/java/com/konggogi/veganlife/mealdata/domain/MealData.java
  src/main/java/com/konggogi/veganlife/mealdata/domain/OwnerType.java
  src/main/java/com/konggogi/veganlife/mealdata/domain/PersonalMealData.java
  src/main/java/com/konggogi/veganlife/mealdata/domain/mapper/MealDataDtoMapper.java
  src/main/java/com/konggogi/veganlife/mealdata/domain/mapper/MealDataMapper.java
  src/main/java/com/konggogi/veganlife/mealdata/repository/MealDataRepository.java
  src/main/java/com/konggogi/veganlife/mealdata/repository/PersonalMealDataRepository.java
  src/main/java/com/konggogi/veganlife/mealdata/service/MealDataQueryService.java
  src/main/java/com/konggogi/veganlife/mealdata/service/MealDataSearchService.java
  src/main/java/com/konggogi/veganlife/mealdata/service/PersonalMealDataQueryService.java
  src/main/java/com/konggogi/veganlife/mealdata/service/dto/MealDataDetailsDto.java
  src/main/java/com/konggogi/veganlife/mealdata/service/dto/MealDataListDto.java
  src/test/java/com/konggogi/veganlife/config/MapStructConfig.java
  src/test/java/com/konggogi/veganlife/mealdata/controller/MealDataControllerTest.java
  src/test/java/com/konggogi/veganlife/mealdata/fixture/MealDataFixture.java
  src/test/java/com/konggogi/veganlife/mealdata/fixture/PersonalMealDataFixture.java
  src/test/java/com/konggogi/veganlife/mealdata/repository/MealDataRepositoryTest.java
  src/test/java/com/konggogi/veganlife/mealdata/service/MealDataQueryServiceTest.java
  src/test/java/com/konggogi/veganlife/mealdata/service/MealDataSearchServiceTest.java
Labels: feature, fix

#113 식사 기록 등록 API 구현
  src/main/java/com/konggogi/veganlife/meallog/controller/MealLogController.java
  src/main/java/com/konggogi/veganlife/meallog/controller/dto/request/MealAddRequest.java
  src/main/java/com/konggogi/veganlife/meallog/controller/dto/request/MealLogAddRequest.java
  src/main/java/com/konggogi/veganlife/meallog/domain/Meal.java
  src/main/java/com/konggogi/veganlife/meallog/domain/MealLog.java
  src/main/java/com/konggogi/veganlife/meallog/domain/MealType.java
  src/main/java/com/konggogi/veganlife/meallog/domain/mapper/MealLogMapper.java
  src/main/java/com/konggogi/veganlife/meallog/domain/mapper/MealMapper.java
  src/main/java/com/konggogi/veganlife/meallog/repository/MealLogRepository.java
  src/main/java/com/konggogi/veganlife/meallog/repository/MealRepository.java
  src/main/java/com/konggogi/veganlife/meallog/service/MealLogAddService.java
  src/main/java/com/konggogi/veganlife/meallog/service/MealLogService.java
  src/main/java/com/konggogi/veganlife/meallog/service/MealService.java
Labels: feature

#115 MemberQueryService의 findMemberById를 search() 변경
  src/main/java/com/konggogi/veganlife/meallog/service/MealLogAddService.java
  src/main/java/com/konggogi/veganlife/member/controller/MemberController.java
  src/main/java/com/konggogi/veganlife/member/service/MemberQueryService.java
  src/main/java/com/konggogi/veganlife/member/service/MemberService.java
  src/test/java/com/konggogi/veganlife/member/controller/MemberControllerTest.java
  src/test/java/com/konggogi/veganlife/member/service/MemberQueryServiceTest.java
  src/test/java/com/konggogi/veganlife/member/service/MemberServiceTest.java
Labels: refactor

#120 Post 관련 도메인, 게시글 등록 API, 관련 테스트 구현
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/post.adoc
  src/main/java/com/konggogi/veganlife/global/annotation/ListStringValidator.java
  src/main/java/com/konggogi/veganlife/global/annotation/StringElementLength.java
  src/main/java/com/konggogi/veganlife/post/controller/PostController.java
  src/main/java/com/konggogi/veganlife/post/controller/dto/request/PostAddRequest.java
  src/main/java/com/konggogi/veganlife/post/controller/dto/response/PostAddResponse.java
  src/main/java/com/konggogi/veganlife/post/domain/Post.java
  src/main/java/com/konggogi/veganlife/post/domain/PostImage.java
  src/main/java/com/konggogi/veganlife/post/domain/PostTag.java
  src/main/java/com/konggogi/veganlife/post/domain/Tag.java
  src/main/java/com/konggogi/veganlife/post/domain/mapper/PostImageMapper.java
  src/main/java/com/konggogi/veganlife/post/domain/mapper/PostMapper.java
  src/main/java/com/konggogi/veganlife/post/domain/mapper/TagMapper.java
  src/main/java/com/konggogi/veganlife/post/repository/PostImageRepository.java
  src/main/java/com/konggogi/veganlife/post/repository/PostRepository.java
  src/main/java/com/konggogi/veganlife/post/repository/PostTagRepository.java
  src/main/java/com/konggogi/veganlife/post/repository/TagRepository.java
  src/main/java/com/konggogi/veganlife/post/service/PostService.java
  src/test/java/com/konggogi/veganlife/config/MapStructConfig.java
  src/test/java/com/konggogi/veganlife/post/controller/PostControllerTest.java
  src/test/java/com/konggogi/veganlife/post/domain/PostTest.java
  src/test/java/com/konggogi/veganlife/post/fixture/PostFixture.java
  src/test/java/com/konggogi/veganlife/post/fixture/PostImageFixture.java
  src/test/java/com/konggogi/veganlife/post/fixture/TagFixture.java
  src/test/java/com/konggogi/veganlife/post/repository/TagRepositoryTest.java
  src/test/java/com/konggogi/veganlife/post/service/PostServiceTest.java
Labels: feature

#121 WebClientResponseException 예외 핸들링
  src/main/java/com/konggogi/veganlife/global/advice/member/MemberControllerAdvice.java
  src/main/java/com/konggogi/veganlife/global/exception/ErrorCode.java
  src/main/java/com/konggogi/veganlife/global/security/exception/InvalidOauthTokenException.java
  src/main/java/com/konggogi/veganlife/member/service/OauthService.java
Labels: bug, fix

#118 Meal, MealLog 엔티티 연관관계 수정
  src/main/java/com/konggogi/veganlife/meallog/controller/MealLogController.java
  src/main/java/com/konggogi/veganlife/meallog/controller/dto/request/MealLogAddRequest.java
  src/main/java/com/konggogi/veganlife/meallog/domain/Meal.java
  src/main/java/com/konggogi/veganlife/meallog/domain/MealLog.java
  src/main/java/com/konggogi/veganlife/meallog/domain/mapper/MealLogMapper.java
  src/main/java/com/konggogi/veganlife/meallog/domain/mapper/MealMapper.java
  src/main/java/com/konggogi/veganlife/meallog/service/MealLogAddService.java
  src/main/java/com/konggogi/veganlife/meallog/service/MealLogService.java
  src/main/java/com/konggogi/veganlife/meallog/service/MealService.java
Labels: feature, fix

#123 식사 기록 등록 단위 테스트 + ErrorCode 이름 수정
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/meal-log.adoc
  src/main/java/com/konggogi/veganlife/global/exception/ErrorCode.java
  src/main/java/com/konggogi/veganlife/mealdata/service/MealDataQueryService.java
  src/test/java/com/konggogi/veganlife/config/MapStructConfig.java
  src/test/java/com/konggogi/veganlife/mealdata/controller/MealDataControllerTest.java
  src/test/java/com/konggogi/veganlife/mealdata/fixture/MealDataFixture.java
  src/test/java/com/konggogi/veganlife/mealdata/repository/MealDataRepositoryTest.java
  src/test/java/com/konggogi/veganlife/mealdata/service/MealDataQueryServiceTest.java
  src/test/java/com/konggogi/veganlife/meallog/controller/MealLogControllerTest.java
  src/test/java/com/konggogi/veganlife/meallog/fixture/MealFixture.java
  src/test/java/com/konggogi/veganlife/meallog/fixture/MealLogFixture.java
  src/test/java/com/konggogi/veganlife/meallog/repository/MealLogRepositoryTest.java
  src/test/java/com/konggogi/veganlife/meallog/service/MealLogServiceTest.java
Labels: fix, test

#125 mapper `@Spy` 애노테이션 적용
  src/test/java/com/konggogi/veganlife/post/service/PostServiceTest.java
Labels: refactor

#126 금일 섭취량 조회 API 구현 및 테스트
  src/docs/asciidoc/member.adoc
  src/main/java/com/konggogi/veganlife/meallog/repository/MealLogRepository.java
  src/main/java/com/konggogi/veganlife/member/controller/MemberController.java
  src/main/java/com/konggogi/veganlife/member/controller/dto/response/TodayIntakeResponse.java
  src/main/java/com/konggogi/veganlife/member/domain/mapper/NutrientsMapper.java
  src/main/java/com/konggogi/veganlife/member/service/NutrientsQueryService.java
  src/main/java/com/konggogi/veganlife/member/service/dto/IntakeNutrients.java
  src/test/java/com/konggogi/veganlife/config/MapStructConfig.java
  src/test/java/com/konggogi/veganlife/meallog/fixture/MealLogFixture.java
  src/test/java/com/konggogi/veganlife/meallog/repository/MealLogRepositoryTest.java
  src/test/java/com/konggogi/veganlife/member/controller/MemberControllerTest.java
  src/test/java/com/konggogi/veganlife/member/service/NutrientsQueryServiceTest.java
Labels: feature

#130 주간 섭취량 조회 API 구현
  src/docs/asciidoc/member.adoc
  src/main/java/com/konggogi/veganlife/meallog/domain/MealType.java
  src/main/java/com/konggogi/veganlife/member/controller/MemberController.java
  src/main/java/com/konggogi/veganlife/member/controller/dto/response/CalorieIntakeResponse.java
  src/main/java/com/konggogi/veganlife/member/domain/mapper/NutrientsMapper.java
  src/main/java/com/konggogi/veganlife/member/service/NutrientsQueryService.java
  src/main/java/com/konggogi/veganlife/member/service/dto/CaloriesOfMealType.java
  src/test/java/com/konggogi/veganlife/member/controller/MemberControllerTest.java
  src/test/java/com/konggogi/veganlife/member/fixture/CaloriesOfMealTypeFixture.java
  src/test/java/com/konggogi/veganlife/member/service/NutrientsQueryServiceTest.java
Labels: feature

#138 MealLog에 MealImage 컬럼 추가
  src/main/java/com/konggogi/veganlife/meallog/controller/dto/request/MealLogAddRequest.java
  src/main/java/com/konggogi/veganlife/meallog/domain/MealImage.java
  src/main/java/com/konggogi/veganlife/meallog/domain/MealLog.java
  src/main/java/com/konggogi/veganlife/meallog/domain/mapper/MealImageMapper.java
  src/main/java/com/konggogi/veganlife/meallog/domain/mapper/MealMapper.java
  src/main/java/com/konggogi/veganlife/meallog/repository/MealImageRepository.java
  src/main/java/com/konggogi/veganlife/meallog/service/MealLogService.java
  src/test/java/com/konggogi/veganlife/meallog/controller/MealLogControllerTest.java
  src/test/java/com/konggogi/veganlife/meallog/fixture/MealImageFixture.java
  src/test/java/com/konggogi/veganlife/meallog/fixture/MealLogFixture.java
  src/test/java/com/konggogi/veganlife/meallog/repository/MealLogRepositoryTest.java
  src/test/java/com/konggogi/veganlife/meallog/service/MealLogServiceTest.java
Labels: feature, fix

#139 JwtAuthenticationFilter에서 발생하는 JWT 예외 핸들링
  src/main/java/com/konggogi/veganlife/global/config/SecurityConfig.java
  src/main/java/com/konggogi/veganlife/global/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/konggogi/veganlife/global/security/handler/JwtAuthenticationEntryPoint.java
  src/main/java/com/konggogi/veganlife/global/util/JwtUtils.java
Labels: bug, fix

#140 식사 기록 목록 조회 API 구현
  src/main/java/com/konggogi/veganlife/meallog/controller/MealLogController.java
  src/main/java/com/konggogi/veganlife/meallog/controller/dto/response/MealLogListResponse.java
  src/main/java/com/konggogi/veganlife/meallog/domain/mapper/MealImageMapper.java
  src/main/java/com/konggogi/veganlife/meallog/domain/mapper/MealLogMapper.java
  src/main/java/com/konggogi/veganlife/meallog/domain/mapper/MealMapper.java
  src/main/java/com/konggogi/veganlife/meallog/repository/MealLogRepository.java
  src/main/java/com/konggogi/veganlife/meallog/service/MealLogQueryService.java
  src/main/java/com/konggogi/veganlife/meallog/service/dto/MealLogList.java
  src/test/java/com/konggogi/veganlife/meallog/controller/MealLogControllerTest.java
Labels: feature

#142 식사 기록 목록 조회 API 구현
  src/docs/asciidoc/meal-log.adoc
  src/main/java/com/konggogi/veganlife/meallog/repository/MealLogRepository.java
  src/main/java/com/konggogi/veganlife/member/service/NutrientsQueryService.java
  src/test/java/com/konggogi/veganlife/meallog/controller/MealLogControllerTest.java
  src/test/java/com/konggogi/veganlife/meallog/fixture/MealFixture.java
  src/test/java/com/konggogi/veganlife/meallog/fixture/MealLogFixture.java
  src/test/java/com/konggogi/veganlife/meallog/repository/MealLogRepositoryTest.java
  src/test/java/com/konggogi/veganlife/meallog/service/MealLogQueryServiceTest.java
  src/test/java/com/konggogi/veganlife/member/service/NutrientsQueryServiceTest.java
Labels: fix, test

#143 식사 기록 상세 조회 API 구현
  src/main/java/com/konggogi/veganlife/global/exception/ErrorCode.java
  src/main/java/com/konggogi/veganlife/meallog/controller/MealLogController.java
  src/main/java/com/konggogi/veganlife/meallog/controller/dto/response/MealDetailsResponse.java
  src/main/java/com/konggogi/veganlife/meallog/controller/dto/response/MealLogDetailsResponse.java
  src/main/java/com/konggogi/veganlife/meallog/domain/mapper/MealLogMapper.java
  src/main/java/com/konggogi/veganlife/meallog/domain/mapper/MealMapper.java
  src/main/java/com/konggogi/veganlife/meallog/service/MealLogQueryService.java
  src/main/java/com/konggogi/veganlife/meallog/service/dto/MealLogDetails.java
Labels: feature

#144 식사 기록 상세 조회 API 테스트
  src/docs/asciidoc/meal-log.adoc
  src/test/java/com/konggogi/veganlife/meallog/controller/MealLogControllerTest.java
  src/test/java/com/konggogi/veganlife/meallog/service/MealLogQueryServiceTest.java
Labels: test

#141 게시글 좋아요/좋아요 취소 API 구현
  src/main/java/com/konggogi/veganlife/global/advice/member/MemberControllerAdvice.java
  src/main/java/com/konggogi/veganlife/global/advice/post/PostControllerAdvice.java
  src/main/java/com/konggogi/veganlife/global/exception/ErrorCode.java
  src/main/java/com/konggogi/veganlife/member/exception/DuplicatedNicknameException.java
  src/main/java/com/konggogi/veganlife/member/service/MemberService.java
  src/main/java/com/konggogi/veganlife/post/controller/PostController.java
  src/main/java/com/konggogi/veganlife/post/domain/Post.java
  src/main/java/com/konggogi/veganlife/post/domain/PostLike.java
  src/main/java/com/konggogi/veganlife/post/domain/mapper/PostLikeMapper.java
  src/main/java/com/konggogi/veganlife/post/exception/IllegalLikeStatusException.java
  src/main/java/com/konggogi/veganlife/post/repository/PostLikeRepository.java
  src/main/java/com/konggogi/veganlife/post/service/LikeService.java
  src/main/java/com/konggogi/veganlife/post/service/PostQueryService.java
  src/test/java/com/konggogi/veganlife/member/controller/MemberControllerTest.java
  src/test/java/com/konggogi/veganlife/member/service/MemberServiceTest.java
  src/test/java/com/konggogi/veganlife/post/controller/PostControllerTest.java
Labels: feature

#150 ErrorCode 코드 포맷팅
  src/main/java/com/konggogi/veganlife/global/exception/ErrorCode.java
Labels: fix, refactor

#152 Meal 엔티티 불필요한 필드 삭제, MealLog 상세 조회 관련 dto 수정
  src/main/java/com/konggogi/veganlife/mealdata/controller/dto/response/MealDataDetailsResponse.java
  src/main/java/com/konggogi/veganlife/mealdata/domain/mapper/MealDataMapper.java
  src/main/java/com/konggogi/veganlife/meallog/controller/dto/request/MealAddRequest.java
  src/main/java/com/konggogi/veganlife/meallog/controller/dto/response/MealDetailsResponse.java
  src/main/java/com/konggogi/veganlife/meallog/controller/dto/response/MealImageDetailsResponse.java
  src/main/java/com/konggogi/veganlife/meallog/controller/dto/response/MealLogDetailsResponse.java
  src/main/java/com/konggogi/veganlife/meallog/domain/Meal.java
  src/main/java/com/konggogi/veganlife/meallog/domain/mapper/MealLogMapper.java
  src/main/java/com/konggogi/veganlife/meallog/domain/mapper/MealMapper.java
  src/test/java/com/konggogi/veganlife/meallog/controller/MealLogControllerTest.java
  src/test/java/com/konggogi/veganlife/meallog/fixture/MealFixture.java
  src/test/java/com/konggogi/veganlife/meallog/service/MealLogServiceTest.java
Labels: feature, fix

#153 게시글 좋아요/취소 테스트
  src/docs/asciidoc/meal-log.adoc
  src/docs/asciidoc/oauth.adoc
  src/docs/asciidoc/post.adoc
  src/main/java/com/konggogi/veganlife/post/repository/PostLikeRepository.java
  src/test/java/com/konggogi/veganlife/config/MapStructConfig.java
  src/test/java/com/konggogi/veganlife/post/controller/PostControllerTest.java
  src/test/java/com/konggogi/veganlife/post/repository/PostLikeRepositoryTest.java
  src/test/java/com/konggogi/veganlife/post/service/LikeServiceTest.java
  src/test/java/com/konggogi/veganlife/post/service/PostQueryServiceTest.java
Labels: test

#154 게시글 좋아요 취소 ErrorCode ALREADY_UNLIKED로 변경
  src/test/java/com/konggogi/veganlife/post/controller/PostControllerTest.java
Labels: fix, test

#156 jacoco 설정 추가
  build.gradle
  lombok.config
Labels: chore

#157 월간 섭취량 조회 API
  src/docs/asciidoc/member.adoc
  src/main/java/com/konggogi/veganlife/member/controller/MemberController.java
  src/main/java/com/konggogi/veganlife/member/controller/dto/response/CalorieIntakeResponse.java
  src/main/java/com/konggogi/veganlife/member/domain/mapper/NutrientsMapper.java
  src/main/java/com/konggogi/veganlife/member/service/NutrientsQueryService.java
  src/test/java/com/konggogi/veganlife/member/controller/MemberControllerTest.java
  src/test/java/com/konggogi/veganlife/member/fixture/CaloriesOfMealTypeFixture.java
  src/test/java/com/konggogi/veganlife/member/service/NutrientsQueryServiceTest.java
Labels: feature, test

#158 OauthProvider 지원하지 않는 Provider 예외 테스트 추가
  src/main/java/com/konggogi/veganlife/member/domain/oauth/OauthProvider.java
  src/test/java/com/konggogi/veganlife/member/service/MemberQueryServiceTest.java
  src/test/java/com/konggogi/veganlife/member/service/OauthUserInfoFactoryTest.java
Labels: test

#160 MemberQueryServiceTest, AuthControllerTest 테스트 추가 및 수정
  src/docs/asciidoc/auth.adoc
  src/main/java/com/konggogi/veganlife/member/service/MemberQueryService.java
  src/test/java/com/konggogi/veganlife/member/controller/AuthControllerTest.java
  src/test/java/com/konggogi/veganlife/member/service/MemberQueryServiceTest.java
Labels: test

#163 연간 섭취량 조회 API 구현
  src/docs/asciidoc/member.adoc
  src/main/java/com/konggogi/veganlife/member/controller/MemberController.java
  src/main/java/com/konggogi/veganlife/member/service/NutrientsQueryService.java
  src/test/java/com/konggogi/veganlife/member/controller/MemberControllerTest.java
  src/test/java/com/konggogi/veganlife/member/service/NutrientsQueryServiceTest.java
Labels: feature, test

#165 MealLog API 리팩토링
  src/main/java/com/konggogi/veganlife/meallog/controller/MealLogController.java
  src/main/java/com/konggogi/veganlife/meallog/controller/dto/response/MealLogDetailsResponse.java
  src/main/java/com/konggogi/veganlife/meallog/domain/MealLog.java
  src/main/java/com/konggogi/veganlife/meallog/domain/mapper/MealLogMapper.java
  src/main/java/com/konggogi/veganlife/meallog/service/MealLogQueryService.java
  src/main/java/com/konggogi/veganlife/meallog/service/MealLogService.java
  src/main/java/com/konggogi/veganlife/meallog/service/dto/MealLogDetails.java
  src/main/java/com/konggogi/veganlife/meallog/service/dto/MealLogList.java
  src/test/java/com/konggogi/veganlife/meallog/controller/MealLogControllerTest.java
  src/test/java/com/konggogi/veganlife/meallog/service/MealLogQueryServiceTest.java
  src/test/java/com/konggogi/veganlife/meallog/service/MealLogServiceTest.java
Labels: refactor

#168 식단 기록 삭제 API 구현 & 단위 테스트
  src/docs/asciidoc/meal-log.adoc
  src/main/java/com/konggogi/veganlife/meallog/controller/MealLogController.java
  src/main/java/com/konggogi/veganlife/meallog/domain/MealImage.java
  src/main/java/com/konggogi/veganlife/meallog/service/MealLogService.java
  src/test/java/com/konggogi/veganlife/meallog/controller/MealLogControllerTest.java
  src/test/java/com/konggogi/veganlife/meallog/repository/MealLogRepositoryTest.java
  src/test/java/com/konggogi/veganlife/meallog/service/MealLogServiceTest.java
Labels: feature, test

#169 식품 데이터 등록 API 구현 및 테스트
  src/docs/asciidoc/meal-data.adoc
  src/main/java/com/konggogi/veganlife/mealdata/controller/MealDataController.java
  src/main/java/com/konggogi/veganlife/mealdata/controller/dto/request/MealDataAddRequest.java
  src/main/java/com/konggogi/veganlife/mealdata/domain/MealData.java
  src/main/java/com/konggogi/veganlife/mealdata/domain/MealDataType.java
  src/main/java/com/konggogi/veganlife/mealdata/domain/mapper/MealDataMapper.java
  src/main/java/com/konggogi/veganlife/mealdata/service/MealDataService.java
  src/test/java/com/konggogi/veganlife/mealdata/controller/MealDataControllerTest.java
  src/test/java/com/konggogi/veganlife/mealdata/fixture/MealDataFixture.java
  src/test/java/com/konggogi/veganlife/mealdata/repository/MealDataRepositoryTest.java
  src/test/java/com/konggogi/veganlife/mealdata/service/MealDataServiceTest.java
Labels: feature, test

#172 SSE 연결 API 및 알림 기능 구현
  src/main/java/com/konggogi/veganlife/global/advice/common/GlobalControllerAdvice.java
  src/main/java/com/konggogi/veganlife/global/exception/ErrorCode.java
  src/main/java/com/konggogi/veganlife/sse/controller/SseController.java
  src/main/java/com/konggogi/veganlife/sse/domain/MessageFormatter.java
  src/main/java/com/konggogi/veganlife/sse/domain/Notification.java
  src/main/java/com/konggogi/veganlife/sse/domain/NotificationMessage.java
  src/main/java/com/konggogi/veganlife/sse/domain/NotificationType.java
  src/main/java/com/konggogi/veganlife/sse/domain/mapper/NotificationMapper.java
  src/main/java/com/konggogi/veganlife/sse/exception/SseConnectionException.java
  src/main/java/com/konggogi/veganlife/sse/repository/EmitterRepository.java
  src/main/java/com/konggogi/veganlife/sse/repository/EmitterRepositoryImpl.java
  src/main/java/com/konggogi/veganlife/sse/repository/NotificationRepository.java
  src/main/java/com/konggogi/veganlife/sse/service/NotificationService.java
  src/main/java/com/konggogi/veganlife/sse/service/dto/NotificationData.java
  src/test/java/com/konggogi/veganlife/sse/repository/EmitterRepositoryTest.java
Labels: feature

#174 식품 데이터 검색 기능 수정 및 테스트
  src/main/java/com/konggogi/veganlife/mealdata/controller/MealDataController.java
  src/main/java/com/konggogi/veganlife/mealdata/repository/MealDataRepository.java
  src/main/java/com/konggogi/veganlife/mealdata/service/MealDataQueryService.java
  src/test/java/com/konggogi/veganlife/mealdata/controller/MealDataControllerTest.java
  src/test/java/com/konggogi/veganlife/mealdata/fixture/MealDataFixture.java
  src/test/java/com/konggogi/veganlife/mealdata/repository/MealDataRepositoryTest.java
  src/test/java/com/konggogi/veganlife/mealdata/service/MealDataQueryServiceTest.java
  src/test/java/com/konggogi/veganlife/meallog/controller/MealLogControllerTest.java
  src/test/java/com/konggogi/veganlife/meallog/repository/MealLogRepositoryTest.java
  src/test/java/com/konggogi/veganlife/meallog/service/MealLogQueryServiceTest.java
  src/test/java/com/konggogi/veganlife/meallog/service/MealLogServiceTest.java
  src/test/java/com/konggogi/veganlife/member/service/NutrientsQueryServiceTest.java
Labels: feature, fix

#176 REST-assured 설정
  build.gradle
  src/test/java/com/konggogi/veganlife/mealdata/MealDataIntegrationTest.java
  src/test/java/com/konggogi/veganlife/support/restassured/DatabaseCleaner.java
  src/test/java/com/konggogi/veganlife/support/restassured/DatabaseClearExtension.java
  src/test/java/com/konggogi/veganlife/support/restassured/IntegrationTest.java
Labels: bug, test, chore

#178 mealdata 도메인 end to end 테스트
  src/main/java/com/konggogi/veganlife/global/security/jwt/RefreshToken.java
  src/main/java/com/konggogi/veganlife/meallog/domain/MealImage.java
  src/test/java/com/konggogi/veganlife/mealdata/MealDataIntegrationTest.java
  src/test/java/com/konggogi/veganlife/support/restassured/DatabaseCleaner.java
Labels: bug, fix, test

#179 금일 칼로리 섭취량에 따른 알림 기능 구현
  src/main/java/com/konggogi/veganlife/meallog/service/MealLogService.java
  src/main/java/com/konggogi/veganlife/member/service/IntakeNotifyService.java
  src/main/java/com/konggogi/veganlife/sse/domain/NotificationType.java
  src/main/java/com/konggogi/veganlife/sse/repository/NotificationRepository.java
  src/main/java/com/konggogi/veganlife/sse/service/NotificationService.java
  src/main/java/com/konggogi/veganlife/sse/service/dto/NotificationData.java
  src/test/java/com/konggogi/veganlife/meallog/service/MealLogServiceTest.java
Labels: feature

#181 SseController, NotificationService 테스트
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/sse.adoc
  src/main/java/com/konggogi/veganlife/global/advice/common/GlobalControllerAdvice.java
  src/main/java/com/konggogi/veganlife/global/exception/ErrorCode.java
  src/main/java/com/konggogi/veganlife/member/service/IntakeNotifyService.java
  src/main/java/com/konggogi/veganlife/notification/controller/SseController.java
  src/main/java/com/konggogi/veganlife/notification/domain/MessageFormatter.java
  src/main/java/com/konggogi/veganlife/notification/domain/Notification.java
  src/main/java/com/konggogi/veganlife/notification/domain/NotificationMessage.java
  src/main/java/com/konggogi/veganlife/notification/domain/NotificationType.java
  src/main/java/com/konggogi/veganlife/notification/domain/mapper/NotificationMapper.java
  src/main/java/com/konggogi/veganlife/notification/exception/SseConnectionException.java
  src/main/java/com/konggogi/veganlife/notification/repository/EmitterRepository.java
  src/main/java/com/konggogi/veganlife/notification/repository/EmitterRepositoryImpl.java
  src/main/java/com/konggogi/veganlife/notification/repository/NotificationRepository.java
  src/main/java/com/konggogi/veganlife/notification/service/NotificationService.java
  src/main/java/com/konggogi/veganlife/notification/service/dto/NotificationData.java
  src/test/java/com/konggogi/veganlife/config/MapStructConfig.java
  src/test/java/com/konggogi/veganlife/notification/controller/SseControllerTest.java
  src/test/java/com/konggogi/veganlife/notification/fixture/NotificationFixture.java
  src/test/java/com/konggogi/veganlife/notification/repository/EmitterRepositoryTest.java
  src/test/java/com/konggogi/veganlife/notification/repository/NotificationRepositoryTest.java
  src/test/java/com/konggogi/veganlife/notification/service/NotificationServiceTest.java
Labels: test

#183 IntakeNotifyService 테스트 구현
  src/main/java/com/konggogi/veganlife/global/advice/common/GlobalControllerAdvice.java
  src/main/java/com/konggogi/veganlife/global/advice/notification/SseControllerAdvice.java
  src/main/java/com/konggogi/veganlife/member/service/dto/IntakeNutrients.java
  src/test/java/com/konggogi/veganlife/member/fixture/IntakeNutrientsFixture.java
  src/test/java/com/konggogi/veganlife/member/service/IntakeNotifyServiceTest.java
  src/test/java/com/konggogi/veganlife/notification/service/NotificationServiceTest.java
Labels: test

#185 SSE 재연결 요청 예외 핸들링 + Security 예외 핸들링
  src/main/java/com/konggogi/veganlife/global/advice/common/GlobalControllerAdvice.java
  src/main/java/com/konggogi/veganlife/global/config/SecurityConfig.java
  src/main/java/com/konggogi/veganlife/global/exception/ErrorCode.java
  src/main/java/com/konggogi/veganlife/global/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/konggogi/veganlife/global/security/handler/JwtAuthenticationEntryPoint.java
  src/main/java/com/konggogi/veganlife/global/util/AopUtils.java
Labels: bug, fix
