Repository Vegan-Life/VeganLife-Backend, pull requests merged in 2024-02, with the labels that each got.

#259 [FEATURE] 레시피 검색 API 구현
  src/main/java/com/konggogi/veganlife/recipe/controller/RecipeController.java
  src/main/java/com/konggogi/veganlife/recipe/repository/RecipeRepository.java
  src/main/java/com/konggogi/veganlife/recipe/service/RecipeQueryService.java
  src/main/java/com/konggogi/veganlife/recipe/service/RecipeSearchService.java
Labels: feature

#262 [FIX] 레시피 UI 수정에 따른 API Response 수정
  src/main/java/com/konggogi/veganlife/recipe/controller/RecipeController.java
  src/main/java/com/konggogi/veganlife/recipe/controller/dto/response/RecipeAuthorResponse.java
  src/main/java/com/konggogi/veganlife/recipe/controller/dto/response/RecipeDetailsResponse.java
  src/main/java/com/konggogi/veganlife/recipe/controller/dto/response/RecipeResponse.java
  src/main/java/com/konggogi/veganlife/recipe/domain/mapper/RecipeMapper.java
  src/main/java/com/konggogi/veganlife/recipe/service/RecipeSearchService.java
  src/test/java/com/konggogi/veganlife/recipe/controller/RecipeControllerTest.java
  src/test/java/com/konggogi/veganlife/recipe/service/RecipeSearchServiceTest.java
Labels: fix

#266 [BUG] MealLogMapper에서 MealImage 매핑 시 오류 수정
  src/main/java/com/konggogi/veganlife/meallog/domain/mapper/MealLogMapper.java
Labels: bug

#268 [REFACTOR/ENHANCEMENT] 주간 섭취 칼로리 조회 API 리팩토링
  src/docs/asciidoc/nutrients.adoc
  src/main/java/com/konggogi/veganlife/meallog/domain/mapper/MealLogMapper.java
  src/main/java/com/konggogi/veganlife/meallog/repository/MealLogRepository.java
  src/main/java/com/konggogi/veganlife/meallog/service/MealLogQueryService.java
  src/main/java/com/konggogi/veganlife/member/controller/NutrientsController.java
  src/main/java/com/konggogi/veganlife/member/controller/dto/response/CalorieIntakeResponse.java
  src/main/java/com/konggogi/veganlife/member/domain/mapper/NutrientsMapper.java
  src/main/java/com/konggogi/veganlife/member/service/IntakeNutrientsService.java
  src/main/java/com/konggogi/veganlife/member/service/dto/CaloriesOfMealType.java
  src/main/java/com/konggogi/veganlife/member/service/dto/IntakeCalorie.java
  src/test/java/com/konggogi/veganlife/meallog/repository/MealLogRepositoryTest.java
  src/test/java/com/konggogi/veganlife/meallog/service/MealLogQueryServiceTest.java
  src/test/java/com/konggogi/veganlife/member/controller/NutrientsControllerTest.java
  src/test/java/com/konggogi/veganlife/member/fixture/CaloriesOfMealTypeFixture.java
  src/test/java/com/konggogi/veganlife/member/service/IntakeNutrientsServiceTest.java
Labels: enhancement, refactor, test
