Repository Vegan-Life/VeganLife-Backend, pull requests merged in 2024-03, with the labels that each got.

#271 [INFRA] Github Action 워크플로 구성
  .github/workflows/gradle-publish.yml
Labels: infra

#272 add: gradle.yml
  .github/workflows/gradle.yml
Labels: infra

#273 [INFRA] Github Actions CI 워크플로 구성
  .github/workflows/gradle-publish.yml
  .github/workflows/gradle.yml
Labels: infra

#274 [INFRA] 자동배포 워크플로 구성
  .github/workflows/ci.yml
  .github/workflows/dev.yml
  docker/Dockerfile
Labels: infra

#275 일일/주간/월간/연간 섭취량 조회 API 리팩토링
  build.gradle
  src/docs/asciidoc/oauth.adoc
  src/main/java/com/konggogi/veganlife/meallog/domain/MealLog.java
  src/main/java/com/konggogi/veganlife/meallog/domain/mapper/MealLogMapper.java
  src/main/java/com/konggogi/veganlife/meallog/repository/MealLogRepository.java
  src/main/java/com/konggogi/veganlife/meallog/repository/querydsl/MealLogCustomRepository.java
  src/main/java/com/konggogi/veganlife/meallog/repository/querydsl/MealLogCustomRepositoryImpl.java
  src/main/java/com/konggogi/veganlife/meallog/service/MealLogQueryService.java
  src/main/java/com/konggogi/veganlife/member/controller/NutrientsController.java
  src/main/java/com/konggogi/veganlife/member/domain/mapper/NutrientsMapper.java
  src/main/java/com/konggogi/veganlife/member/service/IntakeNutrientsService.java
  src/main/java/com/konggogi/veganlife/member/service/dto/IntakeCalorie.java
  src/main/java/com/konggogi/veganlife/member/service/dto/IntakeNutrients.java
  src/main/java/com/konggogi/veganlife/member/service/dto/TotalCalorieOfMealType.java
  src/test/java/com/konggogi/veganlife/meallog/repository/MealLogRepositoryTest.java
  src/test/java/com/konggogi/veganlife/meallog/repository/querydsl/MealLogCustomRepositoryImplTest.java
  src/test/java/com/konggogi/veganlife/meallog/service/MealLogQueryServiceTest.java
  src/test/java/com/konggogi/veganlife/member/controller/NutrientsControllerTest.java
  src/test/java/com/konggogi/veganlife/member/fixture/IntakeCalorieFixture.java
  src/test/java/com/konggogi/veganlife/member/service/IntakeNutrientsServiceTest.java
Labels: enhancement, refactor, test

#279 README.md 작성
  README.md
Labels: docs

#280 [INFRA] CI gradlew 작업 수정, CI 결과 Discord 전송
  .github/workflows/ci.yml
  .github/workflows/dev.yml
Labels: infra

#281 README.md 문제 해결 링크 추가
  README.md
Labels: docs
