Repository Vegan-Life/VeganLife-Backend, pull requests merged in 2025-02, with the labels that each got.

#328 피드 수정 요청 시, dto에 기존 이미지 URL 리스트 필드 추가
  build.gradle
  src/main/java/com/konggogi/veganlife/global/exception/ErrorCode.java
  src/main/java/com/konggogi/veganlife/post/controller/PostController.java
  src/main/java/com/konggogi/veganlife/post/controller/dto/request/PostModifyRequest.java
  src/main/java/com/konggogi/veganlife/post/service/PostService.java
  src/test/java/com/konggogi/veganlife/post/controller/PostControllerTest.java
  src/test/java/com/konggogi/veganlife/post/service/PostServiceTest.java
Labels: feature

#329 PostController 테스트 코드 수정
  src/test/java/com/konggogi/veganlife/post/controller/PostControllerTest.java
Labels: test

#331 Feature 330: 레시피 수정 API Request DTO 필드에 기존 이미지 url 리스트 추가
  src/main/java/com/konggogi/veganlife/recipe/controller/RecipeController.java
  src/main/java/com/konggogi/veganlife/recipe/controller/dto/request/RecipeModifyRequest.java
  src/main/java/com/konggogi/veganlife/recipe/domain/mapper/RecipeMapper.java
  src/main/java/com/konggogi/veganlife/recipe/service/RecipeService.java
  src/test/java/com/konggogi/veganlife/recipe/controller/RecipeControllerTest.java
Labels: feature

#333 [FEATURE] 식단 기록 수정 API Request DTO 필드에 기존 이미지 url 리스트 추가
  src/docs/asciidoc/recipe.adoc
  src/main/java/com/konggogi/veganlife/meallog/controller/dto/request/MealLogModifyRequest.java
  src/main/java/com/konggogi/veganlife/meallog/service/MealLogService.java
  src/test/java/com/konggogi/veganlife/meallog/controller/MealLogControllerTest.java
  src/test/java/com/konggogi/veganlife/meallog/service/MealLogServiceTest.java
  src/test/java/com/konggogi/veganlife/recipe/controller/RecipeControllerTest.java
Labels: feature

#335 [#334] fix: 추천 레시피-조회된 레시피의 개수가 0개일 경우 예외처리 추가
  src/main/java/com/konggogi/veganlife/recipe/service/RecipeSearchService.java
Labels: bug
